{{- if .Values.netpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ include "helm-api-cadastro.fullname" . }}-allow-mongodb
 labels: 
     {{- include "helm-api-cadastro.labels" . | nindent 5 }}
  {{- if not .Values.namespace.enabled }}
 namespace: {{ .Values.namespacedef }}
  {{- else }}
 namespace: {{ .Values.namespace.name }}
  {{- end }}
spec:
  podSelector:
   matchLabels:
      {{- include "helm-api-cadastro.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- range .Values.netpolicy.type }}  
   - {{ . }}
  {{- end }} 
  ingress: 
   - from:
   - podSelector:
      matchLabels:
          {{- include "helm-api-cadastro.selectorLabels" . | nindent 6 }}
     ports:
     {{- range .Values.netpolicy.ingress}}
       - protocol: {{.protocol }}
         port: {{ .port }}
     {{- end }}
  egress:
   - to: 
   - podSelector:
      matchLabels:
          {{- include "helm-api-cadastro.selectorLabels" . | nindent 6 }}
     ports:
     {{- range .Values.netpolicy.egress}}
       - protocol: {{ .protocol }}
         port: {{ .port }}
     {{- end }}  
   - to:
     - namespaceSelector:
        matchLabels:
         kubernetes.io/metadata.name: kube-system
       podSelector:
        matchLabels:
         k8s-app: kube-dns
     ports:
     {{- range .Values.netpolicy.namespaceselector}}
       - protocol: {{ .protocol }}
         port: {{ .port }}
     {{- end }}  
   {{- end }}