{{- if .Values.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
 name: {{ .Release.Name }}-role
 labels: 
     {{- include "helm-api-cadastro.labels" . | nindent 5 }}
     {{ .Values.extralabels | nindent 4 }}
rules:
 {{- range .Values.role.rules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
    resources: {{ .resources | toYaml | nindent 4 }}
    verbs: {{ .verbs | toYaml | nindent 4 }}
    {{- if .resourceNames }}
    resourceNames: {{ .resourceNames | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

  