{{- if and (.Values.secret.create) (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  {{ .Values.secret.usernameKey }}: {{ .Values.secret.username | quote}}
  {{ .Values.secret.passwordKey }}: {{ .Values.secret.password }}
{{- end }}
