{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-api-cadastro.serviceAccountName" . }}
  labels:
    {{- include "helm-api-cadastro.labels" . | nindent 4 }}
  {{- if not .Values.namespace.enabled }}
  namespace: {{ .Values.namespacedef }}
  {{- else }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}  
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
