{
 "title": "Api Cadastro",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tempo de Resposta",
   "type": "timeseries",
   "description": "Usado para visualizar a Latência da aplicação",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "requisições HTTP recebidas",
   "type": "timeseries",
   "description": "Fundamental para dimensionamento e load balancing.",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{code=\"200\"}[5m])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Requisições Ativas",
   "type": "timeseries",
   "description": "Requisições Ativas. Valores altos indicam congestionamento.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_in_progress{action=\"Get\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Uso de CPU % do limite do recurso",
   "type": "timeseries",
   "description": "uso da cpu em relação ao limite do recurso no pod. ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image=\"docker.io/patrickpk4/catalogo:v1.0\"}[5m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"api.+\"}) * 100",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "description": "Monitora a saturação total do Pod em relação aos limits do Kubernetes.",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "  sum(\n     \n    container_memory_working_set_bytes{pod=~\"api.+\"} / (1024*1024)\n  )\n",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Taxa de coleta G2",
   "type": "timeseries",
   "description": "registra o número total de coletas de lixo que ocorreram desde o início do processo da sua aplicação .NET.\n\nNormal\tBaixa e estável (ex: ~0.001/s).\tCarga normal da aplicação.\tApenas monitorar.\nAtenção\tAumento súbito (ex: >0.01/s).\tPossível memory leak ou alta alocação.\tInvestigar métricas de heap (dotnet_gc_heap_size).\nCrítico\tAlta e sustentada (>0.1/s).\tMemory leak confirmado. Performance degradada.\tAnalisar dump de memória, revisar código.\n",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "rate(dotnet_collection_count_total{generation=\"2\"}[5m])\n",
     "legendFormat": "generation {{generation}}"
    }
   ]
  },
  {
   "title": "% de requisições que são erros 4xx.",
   "type": "timeseries",
   "description": "Taxa de Erros do Cliente (4xx).",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum(rate(http_requests_received_total{code=~\"4..\"}[5m])) / sum(rate(http_requests_received_total[5m])) ) * 100",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros no Servidor ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "http_requests_received_total{code=~\"5..\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}