{
 "title": "MongoDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Leituras/Escritas/Comandos",
   "type": "timeseries",
   "description": "Taxa de comandos de leitura.\nTaxa de comandos de inserção.\nContador de comandos não-CRUD (ex: comandos de administração).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"query\"}[5m])",
     "legendFormat": "{{legacy_op_type}} "
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"insert\"}[5m])",
     "legendFormat": "{{legacy_op_type}} "
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"command\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Conexões",
   "type": "gauge",
   "description": "todas as conexões.",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_ss_connections", "legendFormat": "{{conn_type}}" }
   ]
  },
  {
   "title": "Tráfego de Rede",
   "type": "timeseries",
   "description": "Bytes de dados entrando e saindo.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn[5m])",
     "legendFormat": "Bytes de dados entrando"
    },
    {
     "expr": "  rate(mongodb_ss_network_bytesOut[5m])",
     "legendFormat": "Bytes de dados saindo"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Limite do recurso para o mongodb",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"mongodb\"}[3m]) ) / sum(kube_pod_container_resource_limits{container=\"mongodb\", resource=\"cpu\", pod=\"mongodb-statefulset-0\"}) * 100\n\n\n\n \n\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "escrita e leitura no disco ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_sda_reads[5m])",
     "legendFormat": "leitura"
    },
    {
     "expr": "rate(mongodb_sys_disks_sda_writes[5m])",
     "legendFormat": "escrita"
    }
   ]
  },
  {
   "title": "Memoria",
   "type": "timeseries",
   "description": "consumo da memoria em relação ao limite do recurso. ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\nsum(container_memory_working_set_bytes{container=\"mongodb\"} ) /  sum(kube_pod_container_resource_limits{container=\"mongodb\", resource=\"memory\",pod=\"mongodb-statefulset-0\"}) * 100",
     "legendFormat": "memoria"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "mongodb_ss_uptimeEstimate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Saúde",
   "type": "stat",
   "description": "Retorna 1 (saudável) ou 0 (não saudável).",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_rs_members_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Numero de Replicas",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"mongodb-hpa\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}